### ISSUE TITLE
Seeking guidance on reproducing paper results with provided config

### ISSUE THREAD

**Issue by MagicTZ** [3DAgentWorld/OpenGS-SLAM#6]
Hi, thanks for your excellent work!

I’m trying to reproduce the results from the paper using the default base_config.yaml provided in the repository, but my results **(test in 100613.yaml)** are noticeably worse.

![Image](https://github.com/user-attachments/assets/3eedb707-7913-448d-8555-4945be1ded5d)

![Image](https://github.com/user-attachments/assets/aab06766-75f8-4626-884d-85601e111d5d)

```
{
    "rmse": 0.4715244245282105,
    "mean": 0.43195006852728046,
    "median": 0.370154700846674,
    "std": 0.18908839527040722,
    "min": 0.08403950664170633,
    "max": 0.9655146783936671,
    "sse": 7.114729053653122
}

{
    "mean_psnr": 22.75845586603338,
    "mean_ssim": 0.7847526105967435,
    "mean_lpips": 0.41799326412605514
}
```

Could you kindly:

1. _Confirm whether the provided config.yaml is the exact configuration used in the paper?_
2. _Share any additional experimental details (e.g., hyperparameters, data preprocessing, random seeds) that might affect reproducibility?_

For reference, here’s the base_config.yaml I used:
```yaml
Results:
  save_results: True
  save_dir: "results"
  save_trj: True
  save_trj_kf_intv: 10
  use_gui: False
  eval_rendering: True
  use_wandb: False
  color_refinement: True

Dataset:
  type: 'waymo'
  sensor_type: 'monocular'
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01

Training:
  init_itr_num: 1050
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  tracking_itr_num: 100
  mapping_itr_num: 150
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 2001
  size_threshold: 20
  kf_interval: 5
  window_size: 8
  pose_window: 3
  edge_threshold: 1.1
  rgb_boundary_threshold: 0.01

  kf_translation: 0.08
  kf_min_translation: 0.05
  kf_overlap: 0.9
  kf_cutoff: 0.3
  prune_mode: 'slam'
  single_thread: False
  spherical_harmonics: False

  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001

opt_params:
  iterations: 30000
  position_lr_init: 0.0016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False

```
